version: "3"

services:
  story:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - ./:/root
      - /root/node_modules
    ports:
      - 4000:4000
      - 9000:9000 # Debugger
      - 9005:9005 # Debugger
