name: deploy-storyform-staging-gateway

on:
  workflow_dispatch:

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT }}
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "staging-story-gateway"
          source: ./
          region: asia-northeast1
          project_id: story-4a1ac
