name: deploy-storyform-gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_GITHUB_ACTIONS_SERVICE_ACCOUNT }}
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "story-gateway"
          source: ./
          region: asia-northeast1
      - name: "output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
